/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ophl' at '4/26/16 11:38 AM' with Gradle 2.12
 *
 * @author ophl, @date 4/26/16 11:38 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
